on: issues

name: Create pull request from issue

jobs:
  run:
    name: Issue opened
    if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create dummy commits
        run: |
          git config user.name 'Christopher Obbard'
          git config user.email 'obbardc@users.noreply.github.com'
          mkdir -p scratch
          FILE="scratch/test-data-$RANDOM"
          echo "Test things!" > $FILE
          git add $FILE
          git commit -sm "Automated commit added by CI"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automated PR: ${{ github.event.issue.title }}'
          body: |
            Issue created by automation

            ${{ github.event.issue.body }}

            Closes: #${{ github.event.issue.number }}
          assignees: obbardc
          reviewers: obbardc
          labels: automated-pr-from-issue
          branch: auto/issue/${{ github.event.issue.number }}
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Comment on issue
        uses: actions/github-script@3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for your submission'
            })
