on: issues

jobs:
  issue:
    name: Issue
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Issue created/updated ID ${{ github.event.issue.number }}"
          export
          echo "Testing what's inside workspace"
          ls -la $GITHUB_WORKSPACE
